python_cms/blueprints/auth.py
from flask import Blueprint, redirect, request, url_for
import requests
from oauthlib.oauth2 import WebApplicationClient
from os import environ
import json
from python_cms.models.user import UserModel
from flask_login import login_user, logout_user

auth_blueprint = Blueprint('auth', __name__)

GOOGLE_CLIENT_ID = environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = environ.get("GOOGLE_CLIENT_SECRET")

GOOGLE_DISCOVERY_URL = (
    "https://accounts.google.com/.well-known/openid-configuration")

client = WebApplicationClient(GOOGLE_CLIENT_ID)


@auth_blueprint.route("/login")
def login():
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  authorization_endpoint = google_provider_cfg["authorization_endpoint"]

  request_uri = client.prepare_request_uri(
      authorization_endpoint,
      redirect_uri=request.host_url + "authorize",
      scope=["openid", "email", "profile"],
  )

  return redirect(request_uri)


@auth_blueprint.route("/authorize")
def authorize():
  code = request.args.get("code")
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  token_endpoint = google_provider_cfg["token_endpoint"]
  token_url, headers, body = client.prepare_token_request(
      token_endpoint,
      authorization_response=request.url,
      redirect_url=request.base_url,
      code=code)
  token_response = requests.post(token_url,
                                 headers=headers,
                                 data=body,
                                 auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET))

  print(token_response.json())
  client.parse_request_body_response(json.dumps(token_response.json()))

  # Now that we have the token, let's find and return the profile info
  userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
  uri, headers, body = client.add_token(userinfo_endpoint)
  userinfo_response = requests.get(uri, headers=headers)

  # The userinfo_response object contains the user's information
  print(userinfo_response.json())

  if userinfo_response.json().get("email_verified"):
    unique_id = userinfo_response.json()["sub"]
    users_email = userinfo_response.json()["email"]
    picture = userinfo_response.json()["picture"]
    users_name = userinfo_response.json()["name"]
    user = UserModel(id=unique_id,
                     email=users_email,
                     name=users_name,
                     picture=picture)

    # if the user doesn't exist, create a new user
    if not UserModel.get(unique_id):
      user.save()

    # Begin user session by logging the user in
    login_user(user)

    return redirect(url_for("pages.index"))

  else:
    return "User email not available or not verified by Google.", 400


@auth_blueprint.route("/logout")
def logout():
  logout_user()
  return redirect(url_for("pages.index"))

python_cms/blueprints/pages.py
from flask import Blueprint, render_template, request, redirect, send_from_directory, url_for, flash
from flask_login import login_required
from werkzeug.utils import secure_filename
from flask_ckeditor import upload_success, upload_fail
from os import path
import python_cms
from flask_login import current_user
from bs4 import BeautifulSoup

from python_cms.forms.post_form import PostForm
from python_cms.models.post import PostModel
from python_cms.models.category import CategoryModel

pages_blueprint = Blueprint('pages', __name__)


@pages_blueprint.route("/")
def index():
  posts = PostModel.get_all()
  for post in posts:
    category = CategoryModel.get(post.category_id)
    post.category = category.name
  return render_template("index.html.j2", posts=posts)


@pages_blueprint.route("/about")
def about():
  return render_template("about.html.j2")


@pages_blueprint.route("/post/<int:post_id>")
def view_post(post_id):
  post = PostModel.get(post_id)
  post.body = post.body.decode('utf-8')
  return render_template("post.html.j2", post=post)


@pages_blueprint.route("/post/delete/<int:post_id>")
@login_required
def delete_post(post_id):
  post = PostModel.get(post_id)
  user = current_user.get_id()
  posts = PostModel.get_all()
  if post.author_id == user:
    post.delete()
    flash(f"Post with title: {post.title} is deleted!", "success")
    return redirect(url_for("pages.index"))
  else:
    print("You are not authorized to delete this content!")
  return render_template("index.html.j2", posts=posts), 403


@pages_blueprint.route("/post/edit/<string:post_id>", methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
  if request.method == "GET":
    post = PostModel.get(post_id)
    user = current_user.get_id()
    posts = PostModel.get_all()
    if post.author_id == user:
      form = PostForm()
      form.category.choices = [
          (1, 'Sports'),
          (2, 'Travel'),
          (3, 'Music'),
          (4, 'Food'),
      ]
      form.category.default = post.category_id
      form.process()
      form.title.data = post.title
      form.teaser_image.data = post.teaser_image
      form.body.data = post.body.decode('utf-8')
      form.promoted.data = post.promoted
      return render_template(
          "edit_post.html.j2",
          form=form,
          post_id=post_id,
      )
    else:
      print("You are not authorized to delete this content!")
    return render_template("index.html.j2", posts=posts), 403
  elif request.method == "POST":
    posts = PostModel.get_all()
    post = PostModel.get(post_id)
    form = PostForm()
    post.title = request.form["title"]
    image = request.form.get("original_teaser_image", "")
    if image == "":
      file = request.files["teaser_image"]
      filename = secure_filename(file.filename)
      post.teaser_image = filename
    else:
      post.teaser_image = request.form.get("original_teaser_image", "")
    post.body = request.form["body"].encode('utf-8')
    post.promoted = form.promoted.data
    post.category_id = request.form["category"]
    post.save()
    flash(f"Post with title: {post.title} edited successfully", "success")
    return redirect(url_for("pages.index"))


VALID_TAGS = [
    'div', 'br', 'p', 'h1', 'h2', 'img', 'h3', 'ul', 'li', 'em', 'strong', 'a',
    'b'
    'blockquote'
]


def sanitize_html(value):

  soup = BeautifulSoup(value, features="html.parser")

  for tag in soup.findAll(True):
    if tag.name not in VALID_TAGS:
      tag.extract()

  return soup.renderContents()


@pages_blueprint.route("/add", methods=["GET", "POST"])
@login_required
def create_post():
  form = PostForm()
  form.category.choices = [
      (1, 'Sports'),
      (2, 'Travel'),
      (3, 'Music'),
      (4, 'Food'),
  ]
  if request.method == "POST" and form.validate_on_submit():
    # print(json.dumps(request.form, indent=2))
    body = request.form["body"]
    clean_body = sanitize_html(body)
    title = request.form["title"]
    user = current_user.get_id()
    category_id = request.form["category"]
    if form.promoted.data:
      promoted = bool(form.promoted.data)
    else:
      promoted = 0

    file = request.files["teaser_image"]
    if file:
      filename = secure_filename(file.filename)
      file.save(path.join(python_cms.ROOT_PATH, 'files_upload', filename))
    else:
      filename = ""

    post = PostModel(
        title=title,
        body=clean_body,
        user_id=user,
        teaser_image=filename,
        promoted=promoted,
        category_id=category_id,
    )
    post.save()
    flash(f"Post with title: {title} created successfully", "success")
    return redirect(url_for("pages.create_post"))
  print(form.errors)
  return render_template("create_post.html.j2", form=form)


@pages_blueprint.route("/files/<path:filename>")
def files(filename):
  directory = path.join(python_cms.ROOT_PATH, 'files_upload')
  return send_from_directory(directory=directory, path=filename)


@pages_blueprint.route('/upload', methods=['POST'])
def upload():
  f = request.files.get('upload')
  # Add more validations here
  extension = f.filename.split('.')[-1].lower()
  if extension not in ['jpg', 'gif', 'png', 'jpeg']:
    return upload_fail(message='Image only!')
  directory = path.join(python_cms.ROOT_PATH, 'files_upload')
  f.save(path.join(directory, f.filename))
  url = url_for('pages.files', filename=f.filename)
  return upload_success(
      url,
      filename=f.filename,
  )  # return upload_success call

python_cms/templates/about.html.j2
{% extends "base.html.j2" %}
{% block title %}About page{% endblock %}
{% block content %}
  <h1>About Page</h1>
{% endblock %}

python_cms/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% block headsource %}{% endblock %}
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css')  }}">
</head>
<body>
  <header class="navbar">
    <section class="navbar-section">
      <a href="{{ url_for('pages.index') }}" class="navbar-brand mr-2">Home</a>
      <a href="{{ url_for('pages.about') }}" class="btn btn-link">About</a>
    </section>
    <section class="navbar-section">
      {% if current_user.is_authenticated %}
        <div class="chip user-menu">
          <img class="avatar avatar-sm" src="{{current_user.profile_pic }}" alt="">
          {{ current_user.name }}
          <div class="user-submenu">
            <a href="{{ url_for('pages.create_post') }}">Create post</a>
            <a href="{{ url_for('auth.logout') }}">Log Out</a>
          </div>
        </div>
      {% else %}
        <a href="{{ url_for('auth.login') }}" class="btn btn-link">Log In</a>
      {% endif %}
    </section>
  </header>
  <main>
  {% block content %}{% endblock %}
  </main>
  {% block bodysource %}{% endblock %}
  </main>
</body>
</html>

python_cms/templates/create_post.html.j2
{% extends "base.html.j2" %}
{% block title %}Create Post{% endblock %}
{% block headsource %}
{{ ckeditor.load() }}
{% endblock %}
{% block content %}
<h1>Create post</h1>
{% for message in get_flashed_messages() %}
<div class="toast toast-success">
  <button class="btn btn-clear float-right"></button>
  {{message}}
</div>
{% endfor %}

<form action="/add" method="POST" class="form-group" enctype="multipart/form-data">
  {{ form.csrf_token() }}
  <label for="title">{{ form.title.label }}</label>
  {{ form.title(class="form-input", placeholder="title") }}

  {% if form.errors.teaser_image is defined %}
  {% for error in form.errors.teaser_image %}
  <div class="toast toast-error">
    <button class="btn btn-clear float-right"></button>
    {{error}}
  </div>
  {% endfor %}
  {% endif %}

  <label for="teaser_image">{{ form.teaser_image.label }}</label>
  {{ form.teaser_image(class="form-input") }}
  <label class="form-label">{{ form.category.label }}</label>
  {% for subfield in form.category %}
  <label class="form-radio form-inline">
    {{ subfield }}
    <i class="form-icon"></i> {{ subfield.label.text }}
  </label>
  {% endfor %}
  <br>
  <label for="body">{{ form.body.label }}</label>
  {{ form.body(class="form-input", placeholder="your article goes here", id='body') }}
  {{ form.submit(class="btn btn-primary input-group-btn float-right", id="createPost") }}
  {{ ckeditor.config(name='body') }}
  <div class="form-group">
    <label class="form-switch">
      {{ form.promoted() }}
      <i class="form-icon"></i> Promote on main page
    </label>
  </div>
</form>
{% endblock %}

{% block bodysource %}
<script src="{{url_for('static', filename='create_post.js')}}"></script>
{% endblock %}

python_cms/templates/edit_post.html.j2
{% extends "base.html.j2" %}
{% block title %}Edit post{% endblock %}

{% block headsource %}
{{ ckeditor.load() }}
{% endblock %}

{% block content %}
<h1>Edit post</h1>

{% for message in get_flashed_messages() %}
<div class="toast toast-success">
    <button class="btn btn-clear float-right"></button>
    {{message}}
</div>
{% endfor %}

<form action="/post/edit/{{post_id}}" method="POST" class="form-group" enctype="multipart/form-data">
    {{ form.csrf_token() }}
    <label for="title">{{ form.title.label }}</label>
    {{ form.title(class="form-input", placeholder="title") }}
    <input type="hidden" value="{{ form.teaser_image.data }}" name="original_teaser_image" id="originalTeaserImage">
    {% if form.teaser_image.data!="" %}
    <label for="teaser_image">{{ form.teaser_image.label }}</label>
    {{ form.teaser_image(class="form-input hidden") }}
    <div class="image-container">
        <img class="article-image" src="{{url_for('pages.files', filename=form.teaser_image.data)}}">
        <input style="float:left; margin:0" type="button" value="Delete image"
            class=" btn btn-error tooltip btn-delete-img">
    </div>
    {% else %}
    {% if form.errors.teaser_image is defined %}
    {% for error in form.errors.teaser_image %}
    <div class="toast toast-error">
        <button class="btn btn-clear float-right"></button>
        {{error}}
    </div>
    {% endfor %}
    {% endif %}
    <label for="teaser_image">{{ form.teaser_image.label }}</label>
    {{ form.teaser_image(class="form-input") }}
    {% endif%}
    <label class="form-label">{{ form.category.label }}</label>
    {% for subfield in form.category %}
    <label class="form-radio form-inline">
        {{ subfield }}
        <i class="form-icon"></i> {{ subfield.label.text }}
    </label>
    {% endfor %}
    <br>
    <label for="body">{{ form.body.label }}</label>
    {{ form.body(class="form-input", placeholder="your article goes here", id='body') }}
    {{ form.submit(class="btn btn-primary input-group-btn float-right", id="createPost", value="Save Post") }}
    {{ ckeditor.config(name='body') }}
    <div class="form-group">
        <label class="form-switch">
            {{ form.promoted() }}
            <i class="form-icon"></i> Promote on main page
        </label>
    </div>
</form>
{% endblock %}

{% block bodysource %}
<script src="{{url_for('static', filename='create_post.js')}}"></script>
{% endblock %}

python_cms/templates/index.html.j2
{% extends "base.html.j2" %}
{% block title %}Hello World{% endblock %}
{% block content %}
{% if posts|length == 0 %}
<h1>We have no posts to show</h1>
{% endif %}
{% for message in get_flashed_messages() %}
<div class="toast toast-success">
  <button class="btn btn-clear float-right"></button>
  {{message}}
</div>
{% endfor %}
<div class="columns">
  {% for post in posts|selectattr("promoted", "equalto", True) %}
  <div class="column col-6 col-md-12">
    <div class="card article-card promoted">
      <div class="card-image">
        {% if post.teaser_image =="" %}
        <img src="{{ url_for('static', filename='default.jpg') }}" class="img-responsive article-image" alt="">
        {% else %}
        <img src="/files/{{post.teaser_image}}" class="img-responsive article-image" alt="">
        {% endif %}
      </div>
      <div class="card-header">
        <div class="card-title h5">{{ post.title }}</div>
      </div>
      <div>
        <div class="card-title category">{{ post.category }}</div>
      </div>
      <div class="card-footer">
        <a class="btn btn-primary" href="/post/{{ post.id }}">Read More</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<div class="columns">
  {% for post in posts|selectattr("promoted", "equalto", False) %}
  <div class="column col-6 col-md-12">
    <div class="card article-card">
      <div class="card-image">
        {% if post.teaser_image =="" %}
        <img src="{{ url_for('static', filename='default.jpg') }}" class="img-responsive article-image" alt="">
        {% else %}
        <img src="/files/{{post.teaser_image}}" class="img-responsive article-image" alt="">
        {% endif %}
      </div>
      <div class="card-header">
        <div class="card-title h5">{{ post.title }}</div>
      </div>
      <div>
        <div class="card-title category">{{ post.category }}</div>
      </div>
      <div class="card-footer">
        <a class="btn btn-primary" href="/post/{{ post.id }}">Read More</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<script src="{{url_for('static', filename='create_post.js')}}"></script>
{% endblock %}

python_cms/templates/post.html.j2
{% extends 'base.html.j2' %}
{% block title %} {{ post.title }} {% endblock %}

{% block content %}
{% if post.id is not defined %}
<h1>Post not found</h1>
{% else %}

<form class="form-group" enctype="multipart/form-data">
  <h1>{{ post.title }}
    <a class=" btn btn-error tooltip" data-tooltip="permanently delete this post"
      href='https://flaskcms.com:5000/post/delete/{{ post.id }}' ;">Delete</a>
    <a class=" btn btn-primary tooltip" data-tooltip="edit this post"
      href='https://flaskcms.com:5000/post/edit/{{ post.id }}' ;">Edit</a>
  </h1>
  {% if post.teaser_image ==""%}
  <img src="{{ url_for('static', filename='default.jpg') }}" class="img-responsive article-image" alt="">
  {% else %}
  <img src="/files/{{post.teaser_image}}" class="img-responsive article-image" alt="">
  {% endif %}
  {{ post.body|safe }}
</form>
{% endif %}
{% endblock %}